### ISSUE TITLE
Polyproto interop

### ISSUE THREAD

**Issue by erlend-sh** [nag763/tchatchers#15]
You’ve got a very feature-complete demonstration of a Rust-made chat app here, great work! Pairs nicely with the [chat-server.md](https://github.com/pretzelhammer/rust-blog/blob/master/posts/chat-server.md) tutorial.

Seems you’re done tinkering with this yourself, but I was wondering if you could entertain a question I have, for the sake of other devs I know who might wanna extend your work with a PR/fork.

Could your chat app be used as the foundation for a basic [Polyproto](https://docs.polyphony.chat/Overviews/core/) backend?

**Comment by nag763** [comment]
Hello @erlend-sh !
Thanks for your attention regarding this project, it is a pleasure to see after such a long time some ppl are still having a look at it.
The work made for this project can be used for any usage you want to, with no need of retribution or mention in regards to the original project.
However, understand that everything is not perfect and I would change a lot of things architectural wise if I had enough time to ! 
If you want to check and discuss further on this, let me know so that I reach you on the socials mentioned in your profile ! 
Thanks a lot ! :) 

PS : Public instance was down, I will start it up again soon

**Comment by erlend-sh** [comment]
Yeah let’s talk! I might’ve have found you on Discord, but if I got the wrong guy just send me an email.
